# Generated by Django 4.2.7 on 2025-11-15 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('overcoming_anxiety', 'Overcoming Anxiety'), ('academic_stress', 'Academic Stress'), ('personal_growth', 'Personal Growth'), ('relationships', 'Relationships'), ('self_care', 'Self Care'), ('general_inspiration', 'General Inspiration')], default='general_inspiration', help_text='Story category', max_length=50)),
                ('anonymous', models.BooleanField(default=True, help_text='Display this post anonymously')),
                ('is_approved', models.BooleanField(default=False, help_text='Must be approved by wellness team')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
